apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        pod.alpha.kubernetes.io/init-containers: '
          [
            {
              "name": "copy-custom-config",
              "image": "{{ .Values.image }}",
              "imagePullPolicy": {{ .Values.imagePullPolicy | quote }},
              "command": ["sh", "-c", "mkdir -p /bitnami/mysql/conf && cp -n /bitnami/mysql_config/my.cnf /bitnami/mysql/conf/my_custom.cnf"],
              "volumeMounts": [
                {
                  "name": "config",
                  "mountPath": "/bitnami/mysql_config"
                },
                {
                  "name": "data",
                  "mountPath": "/bitnami/mysql"
                }
              ]
            }
          ]'
    spec:
      containers:
      - name: prom-exporter
        image: "registry.harbor:5000/sky-firmament/mysqld_exporter"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        ports:
        - name: exporter
          containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          value: root:{{ .Values.mysqlRootPassword }}@(localhost:3306)/
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ default "" .Values.mysqlRootPassword | quote }}
        - name: MYSQL_USER
          value: {{ default "" .Values.mysqlUser | quote }}
        - name: MYSQL_PASSWORD
          value: {{ default "" .Values.mysqlPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ default "" .Values.mysqlDatabase | quote }}
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: mysql
          containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin --host $POD_IP ping
          initialDelaySeconds: 120
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin --host $POD_IP ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: /bitnami/mysql
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
